[build-wasm]
canister          = "joltsample"
did_path          = "HelloWorld/joltsample.did"
cpp_paths         = ["./Jolt/Core/Core.h", "./Jolt/*.cpp", "./Jolt/*/*.cpp", "./Jolt/*.h", "./Jolt/*/*.h", "HelloWorld.cpp"]  # Use wildcard pattern to include all .cpp files in src/
cpp_include_dirs = ["Jolt/*"]
cpp_compile_flags = ["-D __x86_64__", "-D JPH_PLATFORM_LINUX"]
cpp_link_flags    = []
c_paths           = []
c_header_paths    = []
c_compile_flags   = []
